* Asahi Guix

[[https://github.com/r0man/asahi-guix/actions/workflows/aarch64-linux-gnu.yml][https://github.com/r0man/asahi-guix/actions/workflows/aarch64-linux-gnu.yml/badge.svg]]
[[https://github.com/r0man/asahi-guix/actions/workflows/x86_64-linux-gnu.yml][https://github.com/r0man/asahi-guix/actions/workflows/x86_64-linux-gnu.yml/badge.svg]]

Asahi Linux on GNU Guix

** Status

Experimental

** Installation

*** Manual

Manual installation of the Guix system from an Asahi Linux installation works.

*** Guix Installer

💣 The installation with the Guix system installer does not work at
the moment. Grub boots into early Guile with keyboard available, but
fails to find the system partitions. Seems to be an issue with USB,
the =/dev/sd*= devices are missing.

**** Installation via USB stick

Build the Guix installer disk image with the Asahi =stable= kernel.

#+begin_src sh :results verbatim
  guix time-machine -C asahi/guix/channels.scm -- system image -L . --image-type=efi-raw asahi/guix/install/base.scm
#+end_src

Build the Guix installer disk image with the Asahi =edge= kernel.

#+begin_src sh :results verbatim
  guix time-machine -C asahi/guix/channels.scm -- system image -L . --image-type=efi-raw asahi/guix/install/edge.scm
#+end_src

Write the installer disk image to the USB stick at =/dev/sda=.

#+begin_src sh :results verbatim
  sudo dd if=/gnu/store/mddmv1mrwln08q3nl5sg7czxd06jws0p-disk-image of=/dev/sda bs=4M status=progress oflag=sync
#+end_src

** Firmware

The firmware required to boot Linux on Apple silicon is proprietary
and cannot be packaged with Asahi Guix. Instead the =asahi-firmware=
Guix package assumes for now that the firmware is available in the
=/boot/efi/vendorfw/firmware.cpio= archive at build time.

When installing Asahi Linux or an UEFI stand-alone system with the
Asahi Linux installer, the Apple silicon firmware will be saved in the
=asahi/all_firmware.tar.gz= archive on the EFI system partition.

The [[https://github.com/AsahiLinux/asahi-scripts/blob/main/asahi-fwextract][asahi-fwextract]] script reads the firmware from the
=asahi/all_firmware.tar.gz= archive and writes it to the =vendorfw=
directory of the EFI system partition as a CPIO and TAR archive. The
EFI system partition should be mounted on =/boot/efi= to make these
firmware files available.

On an Asahi Linux system this should already be the case, on an Asahi
Guix system the EFI system partition can be mounted by adding the
following file system to the =file-systems= field of your
=operating-system= record. Please change the UUID to the one of your
system.

#+begin_src scheme
  (file-system
    (mount-point "/boot/efi")
    (device (uuid "9FBE-130E" 'fat32))
    (type "vfat"))
#+end_src

** Packages

The Asahi Guix channel provides the following packages.

| Guix                | Asahi               |
|---------------------+---------------------|
| alsa-ucm-conf-asahi | [[https://github.com/AsahiLinux/PKGBUILDs/tree/main/alsa-ucm-conf-asahi][alsa-ucm-conf-asahi]] |
| asahi-firmware      | n/a                 |
| asahi-fwextract     | [[https://github.com/AsahiLinux/PKGBUILDs/tree/main/asahi-fwextract][asahi-fwextract]]     |
| asahi-linux         | [[https://github.com/AsahiLinux/PKGBUILDs/tree/main/linux-asahi][linux-asahi]]         |
| asahi-linux-edge    | [[https://github.com/AsahiLinux/PKGBUILDs/tree/main/linux-asahi][linux-asahi]]         |
| asahi-m1n1          | [[https://github.com/AsahiLinux/PKGBUILDs/tree/main/m1n1][m1n1]]                |
| asahi-scripts       | [[https://github.com/AsahiLinux/PKGBUILDs/tree/main/asahi-scripts][asahi-scripts]]       |
| lzfse               | [[https://github.com/AsahiLinux/PKGBUILDs/tree/main/lzfse][lzfse]]               |
| mesa-asahi-edge     | [[https://github.com/AsahiLinux/PKGBUILDs/tree/main/mesa-asahi-edge][mesa-asahi-edge]]     |
| u-boot-apple-m1     | [[https://github.com/AsahiLinux/PKGBUILDs/tree/main/uboot-asahi][uboot-asahi]]         |
