* Asahi Guix

#+AUTHOR: Asahi Guix
#+HTML_HEAD: <link rel="preconnect" href="https://fonts.googleapis.com">
#+HTML_HEAD: <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
#+HTML_HEAD: <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Google+Sans">
#+HTML_HEAD: <style> body { color: #4a4a4a; font-family: 'Google Sans', sans-serif;  text-align: justify; } </style>
#+OPTIONS: num:0
#+OPTIONS: toc:nil
#+PROPERTY: header-args :eval never-export

Asahi Linux on GNU Guix

** Status

💣 Experimental

** Installation

To install a Guix system on Apple Silicon we need /Asahi Linux
Minimal/ or /Asahi Linux Desktop/ installed on your device, as well as
an /UEFI only environment/. At the moment the Asahi Linux installation
is needed to bootstrap the Guix system/installer with the required
firmware. The Guix system itself will be installed into the /UEFI only
environment/.

*** System Preparation

Please follow the Asahi Linux [[https://asahilinux.org/2022/03/asahi-linux-alpha-release/][installation guide]] and install either
the /Asahi Linux Minimal/ or /Asahi Linux Desktop/ system on your
device, as well as an /UEFI only environment/.

Once Asahi Linux and the UEFI only environment are installed, your
disk should look similar to this:

#+begin_src sh :exports both :dir /sudo:: :results verbatim
  sudo fdisk --list /dev/nvme0n1
#+end_src

#+RESULTS:
#+begin_example
Disk /dev/nvme0n1: 1.82 TiB, 2001111162880 bytes, 488552530 sectors
Disk model: APPLE SSD APXXXXX
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

Device              Start       End   Sectors   Size Type
/dev/nvme0n1p1          6    128005    128000   500M unknown
/dev/nvme0n1p2     128006  24542067  24414062  93.1G Apple APFS
/dev/nvme0n1p3   24542068  25152371    610304   2.3G Apple APFS
/dev/nvme0n1p4   25152372  25274483    122112   477M EFI System
/dev/nvme0n1p5   25274484 195440499 170166016   100G Linux filesystem
/dev/nvme0n1p6  195440500 196050803    610304   2.3G Apple APFS
/dev/nvme0n1p7  196050804 196172915    122112   477M EFI System
/dev/nvme0n1p11 487241816 488552524   1310709     5G unknown

Partition table entries are not in disk order.
#+end_example

The =/dev/nvme0n1p3= partition is the [[https://en.wikipedia.org/wiki/Apple_File_System][APFS]] container of the /Asahi
Linux installation/, =/dev/nvme0n1p4= its EFI system partition, and
=/dev/nvme0n1p5= the root partition.

Next comes =/dev/nvme0n1p6=, which is the APFS container of the /UEFI
only environment/, along with its EFI system partition
=/dev/nvme0n1p7=. The root partition of the Guix system itself will be
created during the manual installation or via the installer.

Finally there is the =/dev/nvme0n1p11= partition, which contains the
Apple recovery system, which should *not* be touched or moved around.

Boot into Asahi Linux, [[https://guix.gnu.org/manual/en/html_node/Installation.html][install]] the Guix package manager and follow
either the manual installation (recommended) or the Guix Installer
section of this guide.

*** Manual Installation

The manual installation uses the =guix system init= command to install
a Guix system from the Asahi Linux installation onto the mounted
partitions of the /UEFI only environment/.

**** System configuration

First, lookup the filesystem UUID of the EFI system partition
=/dev/nvme0n1p7= from the /UEFI only environment/.

#+begin_src sh :exports both :results verbatim
  sudo blkid | grep /dev/nvme0n1p7 | sed -n 's/.* UUID="\([^"]*\)".*/\1/p'
#+end_src

#+RESULTS:
#+begin_example
86E8-4498
#+end_example

Create a file called =asahi-guix.scm= and instantiate a Guix operating
system record, configured with the filesystem UUID of your EFI system
partition. In this example, the filesystem UUID is =86E8-4498=.

#+begin_src scheme
  (use-modules (asahi guix system base)
               (gnu))

  (operating-system
    (inherit asahi-operating-system)
    (file-systems (cons* (file-system
                           (device (uuid "86E8-4498" 'fat32))
                           (mount-point "/boot/efi")
                           (needed-for-boot? #t)
                           (type "vfat"))
                         (file-system
                           (device (file-system-label "asahi-guix-root"))
                           (mount-point "/")
                           (needed-for-boot? #t)
                           (type "ext4"))
                         %base-file-systems)))
#+end_src

Build the Guix operating system.

#+begin_src sh
  guix system build --load-path=src asahi-guix.scm
#+end_src

If the operating system builds successfully, we can proceed by
installing the operating system onto the hard drive.

**** System installation

Create a new Linux root partition for the Guix system with =cfdisk=,
format it with the EXT4 filesystem and label it as
=asahi-guix-root=. From now on we assume this new root partition is
created as =/dev/nvme0n1p8=.

#+begin_src sh :results none
  sudo mkfs.ext4 -L asahi-guix-root /dev/nvme0n1p8
#+end_src

💣 Make sure the =metadata_csum_seed= feature isn't enabled on this
device. If it is enabled you might run into the =grub-install: error: unknown filesystem=
error with Grub 2.06.

#+begin_src sh :dir /sudo:: :results verbatim
  tune2fs -O ^metadata_csum_seed /dev/nvme0n1p8
#+end_src

Mount the new root partition =/dev/nvme0n1p8= under =/mnt=, and the
EFI system partition =/dev/nvme0n1p7= under =/mnt/boot/efi=.

#+begin_src sh :results none
  sudo mount /dev/nvme0n1p8 /mnt
  sudo mkdir --parents /mnt/boot/efi
  sudo mount /dev/nvme0n1p7 /mnt/boot/efi
#+end_src

Install the Guix system onto =/mnt=.

#+begin_src sh :results none
  sudo guix time-machine --channels=src/asahi/guix/channels.scm -- \
       system init --load-path=src --system=aarch64-linux asahi-guix.scm /mnt
#+end_src

Finally, umount the EFI system partition and then the root partition.

#+begin_src sh :results none
  sudo umount /mnt/boot/efi
  sudo umount /mnt
#+end_src

Reboot into your new Guix system. If the /UEFI only environment/ is
not your default boot container, you need to switch to the MacOS
recovery system and boot it from there. You can do this, by starting
your device and holding down the power button, until you see it is
booting into the /MacOS startup options/. Once in the startup options,
select the container you want to boot from.

*** Guix Installer

The Guix installation image can be build with Guix installed on a
foreign system that has the firmware available at
=/boot/efi/vendorfw/firmware.cpio=. The firmware is typically
installed on the EFI system partition by the Asahi Linux installer.

**** Installation via USB stick

Build the Guix installer disk image with the Asahi Linux kernel.

#+begin_src sh :results verbatim
  guix time-machine --channels=src/asahi/guix/channels.scm -- \
       system image --load-path=src --image-type=efi-raw --image-size=7.2GiB src/asahi/guix/system/install.scm
#+end_src

Write the installer disk image to the USB stick at =/dev/sda=.

#+begin_src sh :results verbatim
  sudo dd if=/gnu/store/2gcs4ki37ad5qc3y0vrcplca8cr72p9y-disk-image \
       of=/dev/sda bs=4M status=progress oflag=sync
#+end_src

*** Troubleshooting
**** Unsupported Ext4 filesystem feature

When installing the Guix system on an [[https://en.wikipedia.org/wiki/Ext4][Ext4]] filesystem, the
installation of the Grub bootloader might fail with the following
error message:

#+begin_quote
grub-install: error: unknown filesystem
#+end_quote

This seems to be an issue with Grub 2.06 and the =metadata_csum_seed=
filesystem feature being enabled on an Ext4 partition. You can disable
the feature on the device with the following command:

#+begin_src sh :dir /sudo:: :results verbatim
  tune2fs -O ^metadata_csum_seed /dev/<device>
#+end_src

- [[https://mail.gnu.org/archive/html/guix-devel/2024-04/msg00195.html][GNU Guix: Guix bios installation: Grub error: unknown filesystem]]
- [[https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/1844012][Ubuntu Launchpad: Grub2 doesn't recognize ext4 with metadata_csum_seed enabled]]

** Firmware

The firmware required to boot Linux on Apple silicon is proprietary
and cannot be packaged with Asahi Guix. Instead the =asahi-firmware=
Guix package assumes for now that the firmware is available in the
=/boot/efi/vendorfw/firmware.cpio= archive at build time.

When installing Asahi Linux or an UEFI stand-alone system with the
Asahi Linux installer, the Apple silicon firmware will be saved in the
=asahi/all_firmware.tar.gz= archive on the EFI system partition.

The [[https://github.com/AsahiLinux/asahi-scripts/blob/main/asahi-fwextract][asahi-fwextract]] script reads the firmware from the
=asahi/all_firmware.tar.gz= archive and writes it to the =vendorfw=
directory of the EFI system partition as a ~CPIO~ and ~TAR~
archive. The EFI system partition should be mounted on =/boot/efi= to
make these firmware files available.

On an Asahi Linux system this should already be the case, on an Asahi
Guix system the EFI system partition can be mounted by adding the
following file system to the =file-systems= field of your
=operating-system= record. Please change the UUID to the one of your
system.

#+begin_src scheme
  (file-system
    (mount-point "/boot/efi")
    (device (uuid "86E8-4498" 'fat32))
    (type "vfat"))
#+end_src

** Packages

The Asahi Guix channel provides the following packages.

| Asahi Guix Package  | Asahi Linux PKGBUILD |
|---------------------+----------------------|
| asahi-alsa-ucm-conf | [[https://github.com/AsahiLinux/PKGBUILDs/tree/main/alsa-ucm-conf-asahi][alsa-ucm-conf-asahi]]  |
| asahi-audio         | [[https://github.com/chadmed/asahi-audio][asahi-audio]]          |
| asahi-firmware      | n/a                  |
| asahi-fwextract     | [[https://github.com/AsahiLinux/PKGBUILDs/tree/main/asahi-fwextract][asahi-fwextract]]      |
| asahi-linux         | [[https://github.com/AsahiLinux/PKGBUILDs/tree/main/linux-asahi][linux-asahi]]          |
| asahi-linux-edge    | [[https://github.com/AsahiLinux/PKGBUILDs/tree/main/linux-asahi][linux-asahi]]          |
| asahi-m1n1          | [[https://github.com/AsahiLinux/PKGBUILDs/tree/main/m1n1][m1n1]]                 |
| asahi-mesa          | [[https://github.com/AsahiLinux/PKGBUILDs/tree/main/mesa-asahi-edge][mesa-asahi-edge]]      |
| asahi-mesa-headers  | n/a                  |
| asahi-mesa-utils    | n/a                  |
| asahi-scripts       | [[https://github.com/AsahiLinux/PKGBUILDs/tree/main/asahi-scripts][asahi-scripts]]        |
| u-boot-apple-m1     | [[https://github.com/AsahiLinux/PKGBUILDs/tree/main/uboot-asahi][uboot-asahi]]          |

** Thanks

Some code and inspirations were taken from:

- [[https://asahilinux.org/][Asahi Linux]]
- [[https://github.com/daviwil][David Wilson]]
- [[https://guix.gnu.org/][GNU Guix]]
