* Asahi Guix

#+AUTHOR: Asahi Guix
#+HTML_HEAD: <link rel="preconnect" href="https://fonts.googleapis.com">
#+HTML_HEAD: <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
#+HTML_HEAD: <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Google+Sans">
#+HTML_HEAD: <style> body { color: #4a4a4a; font-family: 'Google Sans', sans-serif;  text-align: justify; } </style>
#+OPTIONS: num:0
#+OPTIONS: toc:nil
#+PROPERTY: header-args :eval never-export

[[https://ci.asahi-guix.org/jobset/asahi][https://ci.asahi-guix.org/jobset/asahi/badge.svg?type=0]]

Asahi Guix is a [[https://guix.gnu.org/manual/en/html_node/Channels.html][Guix channel]] to run the [[https://guix.gnu.org/][GNU operating system]] with the
[[https://asahilinux.org/][Asahi Linux]] kernel on [[https://en.wikipedia.org/wiki/Apple_silicon][Apple Silicon]] devices.

** Status

💣 Experimental

** Channel Introduction

The Guix [[https://guix.gnu.org/manual/en/html_node/Channels.html][channel]] [[https://guix.gnu.org/manual/en/html_node/Channel-Authentication.html][introduction]] of the /Asahi Guix/ channel.

#+begin_src scheme
  (channel
   (name 'asahi)
   (url "https://codeberg.org/asahi-guix/channel")
   (branch "main")
   (introduction
    (make-channel-introduction
     "3eeb493b037bea44f225c4314c5556aa25aff36c"
     (openpgp-fingerprint
      "D226 A339 D8DF 4481 5DDE  0CA0 3DDA 5252 7D2A C199"))))
#+end_src

** Installation

To install a Guix system on Apple Silicon we need a [[https://asahilinux.org/fedora/][Fedora Asahi Remix]]
installed on your device, as well as an /UEFI only environment/. At
the moment the Asahi Fedora Remix installation is needed to bootstrap
the Guix system/installer with the required firmware. The Guix system
itself will be installed into the /UEFI only environment/.

*** System Preparation

Please follow the Asahi Fedora Remix [[https://docs.fedoraproject.org/en-US/fedora-asahi-remix/installation/][installation guide]] and install
one of the /Minimal/, /Sever/, /Gnome/ or /KDE Plasma/ operating
systems on your device, as well as an /UEFI only environment/.

Once the Asahi Fedora Remix and the UEFI only environment are
installed, your disk should look similar to this:

#+begin_src sh :exports both :dir /sudo:: :results verbatim
  sudo fdisk --list /dev/nvme0n1
#+end_src

#+RESULTS:
#+begin_example
Disk /dev/nvme0n1: 1.82 TiB, 2001111162880 bytes, 488552530 sectors
Disk model: APPLE SSD APXXXXX
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: gpt
Disk identifier: XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX

Device              Start       End   Sectors   Size Type
/dev/nvme0n1p1          6    128005    128000   500M unknown
/dev/nvme0n1p2     128006  24542067  24414062  93.1G Apple APFS
/dev/nvme0n1p3   24542068  25152371    610304   2.3G Apple APFS
/dev/nvme0n1p4   25152372  25274483    122112   477M EFI System
/dev/nvme0n1p5   25274484 195440499 170166016   100G Linux filesystem
/dev/nvme0n1p6  195440500 196050803    610304   2.3G Apple APFS
/dev/nvme0n1p7  196050804 196172915    122112   477M EFI System
/dev/nvme0n1p11 487241816 488552524   1310709     5G unknown

Partition table entries are not in disk order.
#+end_example

The =/dev/nvme0n1p3= partition is the [[https://en.wikipedia.org/wiki/Apple_File_System][APFS]] container of the /Asahi
Fedora Remix/ installation, =/dev/nvme0n1p4= its EFI system partition,
and =/dev/nvme0n1p5= the root partition.

Next comes =/dev/nvme0n1p6=, which is the APFS container of the /UEFI
only environment/, along with its EFI system partition
=/dev/nvme0n1p7=. The root partition of the Guix system itself will be
created during the manual installation or via the installer.

Finally there is the =/dev/nvme0n1p11= partition, which contains the
Apple recovery system, which should *not* be touched or moved around.

Boot into Fedora Asahi Remix, [[https://guix.gnu.org/manual/en/html_node/Installation.html][install]] the Guix package manager and
follow either the manual installation (recommended) or the Guix
Installer section of this guide.

*** Manual Installation

The manual installation uses the =guix system init= command to install
the Guix system from another GNU/Linux installation onto the mounted
partitions of the /UEFI only environment/.

**** System configuration

First, lookup the filesystem UUID of the EFI system partition
=/dev/nvme0n1p7= from the /UEFI only environment/.

#+begin_src sh :exports both :results verbatim
  sudo blkid | grep /dev/nvme0n1p7 | sed -n 's/.* UUID="\([^"]*\)".*/\1/p'
#+end_src

#+RESULTS:
#+begin_example
86E8-4498
#+end_example

Create a file called =asahi-guix.scm= and instantiate a Guix operating
system record, configured with the filesystem UUID of your EFI system
partition. In this example, the filesystem UUID is =86E8-4498=.

#+begin_src scheme
  (use-modules (asahi guix systems base) (gnu))

  (operating-system
    (inherit asahi-base-os)
    (file-systems (cons* (file-system
                           (device (uuid "86E8-4498" 'fat32))
                           (mount-point "/boot/efi")
                           (needed-for-boot? #t)
                           (type "vfat"))
                         (file-system
                           (device (file-system-label "asahi-guix-root"))
                           (mount-point "/")
                           (needed-for-boot? #t)
                           (type "btrfs"))
                         %base-file-systems)))
#+end_src

Build the Guix operating system.

#+begin_src sh
  guix system build --load-path=modules asahi-guix.scm
#+end_src

If the operating system builds successfully, we can proceed by
installing the operating system onto the hard drive.

**** System installation

Create a new root partition for the Guix system with =cfdisk=, format
it with the BTRFS filesystem and label it as =asahi-guix-root=. From
now on we assume this new root partition is created as
=/dev/nvme0n1p8=.

#+begin_src sh :results none
  sudo mkfs.btrfs -L asahi-guix-root /dev/nvme0n1p8
#+end_src

💣 Make sure the =metadata_csum_seed= feature isn't enabled on this
device. If it is enabled you might run into the =grub-install: error: unknown filesystem=
error with Grub 2.06.

#+begin_src sh :dir /sudo:: :results verbatim
  tune2fs -O ^metadata_csum_seed /dev/nvme0n1p8
#+end_src

Mount the new root partition =/dev/nvme0n1p8= under =/mnt=, and the
EFI system partition =/dev/nvme0n1p7= under =/mnt/boot/efi=.

#+begin_src sh :results none
  sudo mount /dev/nvme0n1p8 /mnt
  sudo mkdir --parents /mnt/boot/efi
  sudo mount /dev/nvme0n1p7 /mnt/boot/efi
#+end_src

Install the Guix system onto =/mnt=.

#+begin_src sh :results none
  sudo guix time-machine --channels=modules/asahi/guix/channels.scm -- \
       system init --load-path=modules --system=aarch64-linux asahi-guix.scm /mnt
#+end_src

Finally, umount the EFI system partition and then the root partition.

#+begin_src sh :results none
  sudo umount /mnt/boot/efi
  sudo umount /mnt
#+end_src

Reboot into your new Guix system. If the /UEFI only environment/ is
not your default boot container, you need to switch to the MacOS
recovery system and boot it from there. You can do this, by starting
your device and holding down the power button, until you see it is
booting into the /MacOS startup options/. Once in the startup options,
select the container you want to boot from.

*** Guix Installer

The Guix installation image can be build with Guix installed on a
foreign system that has the firmware available at
=/boot/efi/vendorfw/firmware.cpio=. The firmware is typically
installed on the EFI system partition by the /Asahi GNU/Linux installer/.

**** Installation via USB stick

Build the Guix installer disk image with the Asahi GNU/Linux kernel.

#+begin_src sh :results verbatim
  guix time-machine --channels=modules/asahi/guix/channels.scm -- \
       system image --load-path=modules --image-type=efi-raw --image-size=7.2GiB modules/asahi/guix/systems/install.scm
#+end_src

Write the installer disk image to the USB stick at =/dev/sda=.

#+begin_src sh :results verbatim
  sudo dd if=/gnu/store/2gcs4ki37ad5qc3y0vrcplca8cr72p9y-disk-image \
       of=/dev/sda bs=4M status=progress oflag=sync
#+end_src

*** Troubleshooting
**** Grub Install: Unknown filesystem

When installing the Guix system on an [[https://en.wikipedia.org/wiki/Ext4][Ext4]] filesystem, the
installation of the Grub bootloader might fail with the following
error message:

#+begin_quote
grub-install: error: unknown filesystem
#+end_quote

This seems to be an issue with Grub 2.06 and the =metadata_csum_seed=
filesystem feature being enabled on an Ext4 partition. You can disable
the feature on the device with the following command:

#+begin_src sh :dir /sudo:: :results verbatim
  tune2fs -O ^metadata_csum_seed /dev/<device>
#+end_src

- [[https://mail.gnu.org/archive/html/guix-devel/2024-04/msg00195.html][GNU Guix: Guix bios installation: Grub error: unknown filesystem]]
- [[https://bugs.launchpad.net/ubuntu/+source/grub2/+bug/1844012][Ubuntu Launchpad: Grub2 doesn't recognize ext4 with metadata_csum_seed enabled]]

**** Asahi installer enters boot loop in step2.sh

After installing Asahi Guix with the [[https://github.com/AsahiLinux/asahi-installer/issues/255][Asahi Linux Installer]] one might
run into a boot loop. This seems to be an Apple bug that happens when
an OS is installed too many times. This was reported at [[https://github.com/AsahiLinux/asahi-installer/issues/255][GH-255]] and can
be fixed with:

#+begin_quote
Boot into recoveryOS (Startup Options), pull up a terminal (it's in
the menu), and run curl -L https://alx.sh/cleanbp | sh. Then try
again.
#+end_quote

** Firmware

The firmware required to boot GNU/Linux on Apple silicon is
proprietary and cannot be packaged with Asahi Guix. Instead, the
=asahi-firmware-service-type= assumes that the firmware is available
in the =/boot/efi/vendorfw/firmware.cpio= archive at boot time.

When installing Asahi Fedora Remix or an UEFI stand-alone system with
the /Asahi GNU/Linux installer/, the Apple silicon firmware will be
saved in the =/boot/efi/asahi/all_firmware.tar.gz= archive on the EFI
system partition.

The [[https://github.com/AsahiLinux/asahi-scripts/blob/main/asahi-fwextract][asahi-fwextract]] script reads the firmware from the
=/boot/efi/asahi/all_firmware.tar.gz= archive and writes it to the
=vendorfw= directory of the EFI system partition as a ~CPIO~ and ~TAR~
archive. The EFI system partition should be mounted on =/boot/efi= to
make these firmware files available.

On an Asahi Fedora Remix system this should already be the case, on an
Asahi Guix system the EFI system partition can be mounted by adding
the following file system to the =file-systems= field of your
=operating-system= record. Please change the UUID to the one of your
system.

#+begin_src scheme
  (file-system
    (mount-point "/boot/efi")
    (device (uuid "86E8-4498" 'fat32))
    (type "vfat"))
#+end_src

** Packages

Overview of packages provided by Asahi Guix and other distributions.

| Asahi Guix          | Arch Linux ARM      | Asahi Remix Fedora | NixOS Apple Silicon |
|---------------------+---------------------+--------------------+---------------------|
| [[https://codeberg.org/asahi-guix/channel/blob/main/modules/asahi/guix/packages/linux.scm#L105][asahi-alsa-ucm-conf]] | [[https://github.com/AsahiLinux/PKGBUILDs/blob/main/alsa-ucm-conf-asahi][alsa-ucm-conf-asahi]] | [[https://src.fedoraproject.org/rpms/alsa-ucm-asahi][alsa-ucm-asahi]]     | [[https://github.com/tpwrules/nixos-apple-silicon/blob/main/apple-silicon-support/packages/alsa-ucm-conf-asahi][alsa-ucm-conf-asahi]] |
| [[https://codeberg.org/asahi-guix/channel/blob/main/modules/asahi/guix/packages/audio.scm#L9][asahi-audio]]         | [[https://github.com/AsahiLinux/asahi-audio][asahi-audio]]         | [[https://src.fedoraproject.org/rpms/asahi-audio][asahi-audio]]        | [[https://github.com/tpwrules/nixos-apple-silicon/blob/main/apple-silicon-support/packages/asahi-audio][asahi-audio]]         |
| [[https://codeberg.org/asahi-guix/channel/blob/main/modules/asahi/guix/packages/firmware.scm#L54][asahi-fwextract]]     | [[https://github.com/AsahiLinux/PKGBUILDs/tree/main/asahi-fwextract][asahi-fwextract]]     | -                  | [[https://github.com/tpwrules/nixos-apple-silicon/blob/main/apple-silicon-support/packages/asahi-fwextract][asahi-fwextract]]     |
| [[https://codeberg.org/asahi-guix/channel/blob/main/modules/asahi/guix/packages/linux.scm#L86][asahi-linux]]         | [[https://github.com/AsahiLinux/PKGBUILDs/blob/main/linux-asahi][linux-asahi]]         | [[https://copr.fedorainfracloud.org/coprs/g/asahi/kernel][@asahi/kernel]]      | [[https://github.com/tpwrules/nixos-apple-silicon/blob/main/apple-silicon-support/packages/linux-asahi][linux-asahi]]         |
| [[https://codeberg.org/asahi-guix/channel/blob/main/modules/asahi/guix/packages/bootloader.scm#L24][asahi-m1n1]]          | [[https://github.com/AsahiLinux/PKGBUILDs/blob/main/m1n1][m1n1]]                | [[https://src.fedoraproject.org/rpms/m1n1][m1n1]]               | [[https://github.com/tpwrules/nixos-apple-silicon/blob/main/apple-silicon-support/packages/m1n1][m1n1]]                |
| [[https://codeberg.org/asahi-guix/channel/blob/main/modules/asahi/guix/packages/gl.scm#L17][asahi-mesa]]          | [[https://github.com/AsahiLinux/PKGBUILDs/blob/main/mesa-asahi-edge][mesa-asahi-edge]]     | [[https://copr.fedorainfracloud.org/coprs/g/asahi/mesa][@asahi/mesa]]        | [[https://github.com/tpwrules/nixos-apple-silicon/blob/main/apple-silicon-support/packages/mesa-asahi-edge][mesa-asahi-edge]]     |
| [[https://codeberg.org/asahi-guix/channel/blob/main/modules/asahi/guix/packages/gl.scm#L71][asahi-mesa-headers]]  | -                   | -                  | -                   |
| [[https://codeberg.org/asahi-guix/channel/blob/main/modules/asahi/guix/packages/gl.scm#L81][asahi-mesa-utils]]    | -                   | -                  | -                   |
| [[https://codeberg.org/asahi-guix/channel/blob/main/modules/asahi/guix/packages/misc.scm#L12][asahi-scripts]]       | [[https://github.com/AsahiLinux/PKGBUILDs/blob/main/asahi-scripts][asahi-scripts]]       | [[https://src.fedoraproject.org/rpms/asahi-scripts][asahi-scripts]]      | -                   |
| [[https://codeberg.org/asahi-guix/channel/blob/main/modules/asahi/guix/packages/bootloader.scm#L24][asahi-u-boot]]        | [[https://github.com/AsahiLinux/PKGBUILDs/tree/main/uboot-asahi][uboot-asahi]]         | [[https://copr.fedorainfracloud.org/coprs/g/asahi/u-boot/][@asahi/u-boot]]      | [[https://github.com/tpwrules/nixos-apple-silicon/blob/main/apple-silicon-support/packages/uboot-asahi][uboot-asahi]]         |

** Thanks

Some code and inspirations were taken from:

- [[https://asahilinux.org/][Asahi GNU/Linux]]
- [[https://github.com/daviwil][David Wilson]]
- [[https://guix.gnu.org/][GNU Guix]]
