#!/usr/bin/env bash

set -euxo pipefail
set -x

ARCH=$(uname -m)

apt-get update
apt-get install xz-utils -y

cd /tmp
wget -nv "https://ci.guix.gnu.org/search/latest/archive?query=spec:tarball+status:success+system:$ARCH-linux+guix-binary.tar.xz" -O "guix-binary-nightly.$ARCH-linux.tar.xz"
tar --warning=no-timestamp -xf "guix-binary-nightly.$ARCH-linux.tar.xz"
mv var/guix /var/ && mv gnu /
mkdir -p ~root/.config/guix
ln -sf /var/guix/profiles/per-user/root/current-guix ~root/.config/guix/current
export GUIX_PROFILE="`echo ~root`/.config/guix/current" ;
source $GUIX_PROFILE/etc/profile
groupadd --system --force guixbuild
for i in `seq -w 1 10`; do
   userdel -f guixbuilder$i || true
   useradd -g guixbuild -G guixbuild         \
           -d /var/empty -s `which nologin`  \
           -c "Guix build user $i" --system  \
           guixbuilder$i;
done;
cp ~root/.config/guix/current/lib/systemd/system/guix-daemon.service /etc/systemd/system/
systemctl start guix-daemon && systemctl enable guix-daemon
mkdir -p /usr/local/bin
cd /usr/local/bin
ln -sf /var/guix/profiles/per-user/root/current-guix/bin/guix
mkdir -p /usr/local/share/info
cd /usr/local/share/info
for i in /var/guix/profiles/per-user/root/current-guix/share/info/*; do
    ln -sf $i;
done
guix archive --authorize < ~root/.config/guix/current/share/guix/bordeaux.guix.gnu.org.pub
guix archive --authorize < ~root/.config/guix/current/share/guix/ci.guix.gnu.org.pub
# guix pull
guix package -i glibc-utf8-locales-2.29
export GUIX_LOCPATH="$HOME/.guix-profile/lib/locale"
guix package -i openssl
guix gc
