#!/usr/bin/env bash

set -euxo pipefail
set -x

BOOT_PARTITION=/dev/sda15
GUIX_COMMIT="${GUIX_COMMIT:-4b3a553ca5ba5ac190739309eb5f7aa8170cf2a8}"
GUIX_PROFILE="${GUIX_PROFILE:-/root/.guix-profile}"
ROOT_PARTITION=/dev/sda1

if mountpoint -q /mnt/boot/efi; then
    echo "*** Formatting boot partition $BOOT_PARTITION..."
    umount /mnt/boot/efi
fi

if mountpoint -q /mnt; then
    echo "*** Formatting boot partition $ROOT_PARTITION..."
    umount /mnt
fi

echo "*** Formatting root partition $ROOT_PARTITION..."
mkfs.ext4 -L root -F $ROOT_PARTITION

echo "*** Formatting boot partition $BOOT_PARTITION..."
mkfs.vfat -n EFI $BOOT_PARTITION

echo "*** Mounting partitions..."
mount $ROOT_PARTITION /mnt
mkdir --parents /mnt/boot/efi
mount $BOOT_PARTITION /mnt/boot/efi

echo "*** Installing Guix..."
bash ${BASH_SOURCE%/*}/install-guix

echo "*** Setting up Guix profile $GUIX_PROFILE..."
source "$GUIX_PROFILE/etc/profile"

echo "*** Initializing Guix system with $GUIX_COMMIT..."
guix time-machine --commit=$GUIX_COMMIT -- \
     system init --load-path=src --system=aarch64-linux modules/asahi/guix/system/server.scm /mnt

echo "*** Unmounting partitions..."
umount /mnt/boot/efi
umount /mnt

echo "*** Installation complete."
