#!/usr/bin/env bash

set -euxo pipefail
set -x

ROOT_PARTITION=/dev/sda1
BOOT_PARTITION=/dev/sda15
GUIX_COMMIT="${GUIX_COMMIT:-4b3a553ca5ba5ac190739309eb5f7aa8170cf2a8}"

bash ${BASH_SOURCE%/*}/install-guix

mkfs.ext4 -L root -F $ROOT_PARTITION
mkfs.vfat -n EFI $BOOT_PARTITION

mount $ROOT_PARTITION /mnt
mkdir --parents /mnt/boot/efi
mount $BOOT_PARTITION /mnt/boot/efi

guix time-machine --commit=$GUIX_COMMIT -- \
     guix system init --load-path=src --system=aarch64-linux src/asahi/guix/system/server.scm /mnt

umount /mnt/boot/efi && umount /mnt
