name: aarch64-linux-gnu
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Guix cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/guix
          key: guix-cache-${{ github.sha }}
          restore-keys: guix-cache-
      - name: Install Guix
        uses: PromyLOPh/guix-install-action@v1
        with:
          channels: |
            (list (channel
                   (name 'asahi)
                   (url "https://github.com/asahi-guix/channel")
                   (branch "main")
                   (introduction
                    (make-channel-introduction
                     "3eeb493b037bea44f225c4314c5556aa25aff36c"
                     (openpgp-fingerprint
                      "D226 A339 D8DF 4481 5DDE  0CA0 3DDA 5252 7D2A C199"))))
                  (channel
                   (name 'guix)
                   (url "https://git.savannah.gnu.org/git/guix.git")
                   (branch "master")
                   (introduction
                    (make-channel-introduction
                     "9edb3f66fd807b096b48283debdcddccfea34bad"
                     (openpgp-fingerprint
                      "BBB0 2DDF 2CEA F6A8 0D1D  E643 A2A0 6DF2 A33A 54FA")))))
      - name: Ensure no locale warning
        run: test -z "$(guix --version 2>&1 >/dev/null)"
      - name: Build alsa-ucm-conf-asahi
        run: guix build -L modules -v 5 --target=aarch64-linux-gnu alsa-ucm-conf-asahi
      - name: Build asahi-audio
        run: guix build -L modules -v 5 --target=aarch64-linux-gnu asahi-audio
      - name: Build asahi-firmware
        run: guix build -L modules -v 5 --target=aarch64-linux-gnu asahi-firmware
      # TODO: Python does not support cross builds
      # - name: Build asahi-fwextract
      #   run: guix build -L modules -v 5 --target=aarch64-linux-gnu asahi-fwextract
      # - name: Build asahi-scripts
      #   run: guix build -L modules -v 5 --target=aarch64-linux-gnu asahi-scripts
      - name: Build asahi-m1n1
        run: guix build -L modules -v 5 --target=aarch64-linux-gnu asahi-m1n1
      # - name: Build u-boot-apple-m1
      #   run: guix build -L modules -v 5 --target=aarch64-linux-gnu u-boot-apple-m1
      # - name: Build mesa-asahi-edge
      #   run: guix build -L modules -v 5 --target=aarch64-linux-gnu mesa-asahi-edge
      # - name: Build asahi-linux
      #   run: guix build -L modules -v 5 --target=aarch64-linux-gnu asahi-linux
      # - name: Build asahi-linux-edge
      #   run: guix build -L modules -v 5 --target=aarch64-linux-gnu asahi-linux-edge
      # - name: Build installer
      #   run: guix system image -L modules --image-type=efi-raw -v 5 --target=aarch64-linux-gnu asahi/guix/installer.scm
