(define-module (asahi guix services console-font)
  #:use-module (gnu packages fonts)
  #:use-module (guix gexp)
  #:use-module (ice-9 match)
  #:export (console-font-terminus))

(define (console-font-terminus config)
  (map (lambda (tty)
         (cons tty (file-append font-terminus "/share/consolefonts/ter-132n")))
       (map car config)))
